### ISSUE TITLE
API - add issuer to participiant

### ISSUE THREAD

**Issue by miekassu** [nscharrenberg/OI4-Blockchain-and-Open-Badges#27]
for teachers and validators add attribute "Issuer" as a list, to link participant to Issuer

**Comment by marioolislaegers** [comment]
Can you elaborate a bit more? Do you want to hold a list of issuer organizations in Teacher and Validator?

**Comment by miekassu** [comment]
Yes

**Comment by marioolislaegers** [comment]
Why would they belong at multiple organizations though?

**Comment by miekassu** [comment]
let's just say that, in the future,  it is more likely that users might be part of multiple organisations.
think about Validators or steering group. they might work in Tillburg and in Eindhoven, maybe they have own organizations.
