### ISSUE TITLE
API - IssuedBadgeClass missing issuerId and validatorId

### ISSUE THREAD

**Issue by miekassu** [nscharrenberg/OI4-Blockchain-and-Open-Badges#49]

**Comment by Rochendiil** [comment]
ASSET ISSUEDBADGECLASS: changed TeacherId to issuerTeacherid. added evidence. added optional validatorId
TRANSACTION ISSUEBADGE: changed badgeId to badgeclassId. changed userId to recipientId. changed teacherId to issuerId. added evidence.
TRANSACTION VALIDATEISSUEDBADGE: added validatorId
