### ISSUE TITLE
API - add validatorId under newbadge validation transacation

### ISSUE THREAD

**Issue by miekassu** [nscharrenberg/OI4-Blockchain-and-Open-Badges#50]

**Comment by Rochendiil** [comment]
ASSET BADGECLASS: made Validatorid optional, badge can now be created without needing to specify validatorId upfront. Removed issuerId . Added creatorTeacherid. Added validatorid. 
TRANSACTION NEWBADGE: removed issuerId. changed teacherId to creatorTeacherId
TRANSACTION VALIDATENEWBADGE: added validatorId
